
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package m4x4.mixtapes.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.Item;

import m4x4.mixtapes.item.YeezysItem;
import m4x4.mixtapes.item.WildSideItem;
import m4x4.mixtapes.item.ViolinItem;
import m4x4.mixtapes.item.RemnantItem;
import m4x4.mixtapes.item.RatsItem;
import m4x4.mixtapes.item.KnobItem;
import m4x4.mixtapes.item.JoyConsItem;
import m4x4.mixtapes.item.HandsomeDevilItem;
import m4x4.mixtapes.item.GoldPlayButtonItem;
import m4x4.mixtapes.item.DrawingTabletItem;
import m4x4.mixtapes.item.CassetteWolfAndRabbitItem;
import m4x4.mixtapes.item.CassetteWantYouGoneItem;
import m4x4.mixtapes.item.CassetteWMTAOItem;
import m4x4.mixtapes.item.CassetteWIGGLECOREItem;
import m4x4.mixtapes.item.CassetteVirtualInsanityItem;
import m4x4.mixtapes.item.CassetteVirginiaItem;
import m4x4.mixtapes.item.CassetteVampireItem;
import m4x4.mixtapes.item.CassetteUniversalCollapseItem;
import m4x4.mixtapes.item.CassetteUndertaleItem;
import m4x4.mixtapes.item.CassetteTulipsItem;
import m4x4.mixtapes.item.CassetteToxicCoffeeItem;
import m4x4.mixtapes.item.CassetteTorielItem;
import m4x4.mixtapes.item.CassetteTomcatItem;
import m4x4.mixtapes.item.CassetteThunderItem;
import m4x4.mixtapes.item.CassetteTheLastGoodbyeItem;
import m4x4.mixtapes.item.CassetteTOTTFIYItem;
import m4x4.mixtapes.item.CassetteTOACWItem;
import m4x4.mixtapes.item.CassetteStrongerItem;
import m4x4.mixtapes.item.CassetteStolasItem;
import m4x4.mixtapes.item.CassetteStillAliveItem;
import m4x4.mixtapes.item.CassetteSteamGardensItem;
import m4x4.mixtapes.item.CassetteSlimeGodItem;
import m4x4.mixtapes.item.CassetteSimoonItem;
import m4x4.mixtapes.item.CassetteScourgeItem;
import m4x4.mixtapes.item.CassetteScienceBlasterItem;
import m4x4.mixtapes.item.CassetteScarletForestItem;
import m4x4.mixtapes.item.CassetteSandcastleKingdomsItem;
import m4x4.mixtapes.item.CassetteSafeAndSoundItem;
import m4x4.mixtapes.item.CassetteSafeAndCYBERItem;
import m4x4.mixtapes.item.CassetteRoxanneItem;
import m4x4.mixtapes.item.CassetteRoseMaryItem;
import m4x4.mixtapes.item.CassetteRockyItem;
import m4x4.mixtapes.item.CassetteRejuvenescenciaItem;
import m4x4.mixtapes.item.CassetteRasputinItem;
import m4x4.mixtapes.item.CassettePuppeteerItem;
import m4x4.mixtapes.item.CassettePizzaTimeItem;
import m4x4.mixtapes.item.CassettePigstepJazzItem;
import m4x4.mixtapes.item.CassettePigstepItem;
import m4x4.mixtapes.item.CassetteParasiteItem;
import m4x4.mixtapes.item.CassetteOliveBranchItem;
import m4x4.mixtapes.item.CassetteOOTItem;
import m4x4.mixtapes.item.CassetteOKULTRAItem;
import m4x4.mixtapes.item.CassetteNormalAlbumItem;
import m4x4.mixtapes.item.CassetteNightmareItem;
import m4x4.mixtapes.item.CassetteMyTimeItem;
import m4x4.mixtapes.item.CassetteMyOrdinaryLifeItem;
import m4x4.mixtapes.item.CassetteMonsterItem;
import m4x4.mixtapes.item.CassetteMaxItem;
import m4x4.mixtapes.item.CassetteMattelItem;
import m4x4.mixtapes.item.CassetteMOVItem;
import m4x4.mixtapes.item.CassetteLucasItem;
import m4x4.mixtapes.item.CassetteLoveMeNormallyItem;
import m4x4.mixtapes.item.CassetteLoveLikeYouItem;
import m4x4.mixtapes.item.CassetteLikeThatItem;
import m4x4.mixtapes.item.CassetteLightsabersItem;
import m4x4.mixtapes.item.CassetteLetterToMyBrotherItem;
import m4x4.mixtapes.item.CassetteLeaveMeBehindItem;
import m4x4.mixtapes.item.CassetteKratosItem;
import m4x4.mixtapes.item.CassetteKickBackItem;
import m4x4.mixtapes.item.CassetteJungleDragonItem;
import m4x4.mixtapes.item.CassetteIslandItem;
import m4x4.mixtapes.item.CassetteIfWeFallItem;
import m4x4.mixtapes.item.CassetteIJAMItem;
import m4x4.mixtapes.item.CassetteIDontWannaBeFreeItem;
import m4x4.mixtapes.item.CassetteHopesAndDreamsItem;
import m4x4.mixtapes.item.CassetteHighwireItem;
import m4x4.mixtapes.item.CassetteHereIComeItem;
import m4x4.mixtapes.item.CassetteHereICome2Item;
import m4x4.mixtapes.item.CassetteGymItem;
import m4x4.mixtapes.item.CassetteGuidingLightItem;
import m4x4.mixtapes.item.CassetteGravityItem;
import m4x4.mixtapes.item.CassetteGoodbyeToAWorldItem;
import m4x4.mixtapes.item.CassetteGoodMorningItem;
import m4x4.mixtapes.item.CassetteGodRaceItem;
import m4x4.mixtapes.item.CassetteGhostsNStuffItem;
import m4x4.mixtapes.item.CassetteGhostItem;
import m4x4.mixtapes.item.CassetteGItem;
import m4x4.mixtapes.item.CassetteFurrymonItem;
import m4x4.mixtapes.item.CassetteFnaf1Item;
import m4x4.mixtapes.item.CassetteFinalDuetItem;
import m4x4.mixtapes.item.CassetteFMTTMItem;
import m4x4.mixtapes.item.CassetteFBCItem;
import m4x4.mixtapes.item.CassetteEternalHorizonsItem;
import m4x4.mixtapes.item.CassetteEisoptrophobiaItem;
import m4x4.mixtapes.item.CassetteDrunkItem;
import m4x4.mixtapes.item.CassetteDreamlandItem;
import m4x4.mixtapes.item.CassetteDoorsItem;
import m4x4.mixtapes.item.CassetteDesmondItem;
import m4x4.mixtapes.item.CassetteDeathByGlamorItem;
import m4x4.mixtapes.item.CassetteDanTDMItem;
import m4x4.mixtapes.item.CassetteDJMMItem;
import m4x4.mixtapes.item.CassetteCosmicItem;
import m4x4.mixtapes.item.CassetteCestLaVieItem;
import m4x4.mixtapes.item.CassetteCaliforniaItem;
import m4x4.mixtapes.item.CassetteBuckleItem;
import m4x4.mixtapes.item.CassetteBox16Item;
import m4x4.mixtapes.item.CassetteBox15Item;
import m4x4.mixtapes.item.CassetteBigPoppaItem;
import m4x4.mixtapes.item.CassetteBettyItem;
import m4x4.mixtapes.item.CassetteBattleBlockItem;
import m4x4.mixtapes.item.CassetteBarbieItem;
import m4x4.mixtapes.item.CassetteBakaMitaiItem;
import m4x4.mixtapes.item.CassetteBadEndTheaterItem;
import m4x4.mixtapes.item.CassetteBTD5Item;
import m4x4.mixtapes.item.CassetteBOWItem;
import m4x4.mixtapes.item.CassetteArchetypeItem;
import m4x4.mixtapes.item.CassetteAnemoiaItem;
import m4x4.mixtapes.item.CassetteAnarchyRainbowItem;
import m4x4.mixtapes.item.CassetteAmongusItem;
import m4x4.mixtapes.item.CassetteAmericanBoyItem;
import m4x4.mixtapes.item.CassetteAlwaysComeBackItem;
import m4x4.mixtapes.item.CassetteAlphaItem;
import m4x4.mixtapes.item.CassetteAllenItem;
import m4x4.mixtapes.item.CassetteAgentRainbowItem;
import m4x4.mixtapes.item.CassetteAfterDarkItem;
import m4x4.mixtapes.item.CassetteAddictItem;
import m4x4.mixtapes.item.CassetteASAFEWORLDItem;
import m4x4.mixtapes.item.CassetteACybersWorldItem;
import m4x4.mixtapes.item.Cassette2TimeZonesItem;
import m4x4.mixtapes.item.Cassette1thot2thotItem;
import m4x4.mixtapes.item.BullPillItem;
import m4x4.mixtapes.item.BlockmanItem;
import m4x4.mixtapes.item.BlankTapeItem;
import m4x4.mixtapes.item.AnnoyingDogItem;
import m4x4.mixtapes.item.AirpodItem;
import m4x4.mixtapes.item.AgentRainbowItem;
import m4x4.mixtapes.MaxsMixtapesMod;

public class MaxsMixtapesModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MaxsMixtapesMod.MODID);
	public static final RegistryObject<Item> BLOCKMAN = REGISTRY.register("blockman", () -> new BlockmanItem());
	public static final RegistryObject<Item> BLANK_TAPE = REGISTRY.register("blank_tape", () -> new BlankTapeItem());
	public static final RegistryObject<Item> AGENT_RAINBOW = REGISTRY.register("agent_rainbow", () -> new AgentRainbowItem());
	public static final RegistryObject<Item> BULL_PILL = REGISTRY.register("bull_pill", () -> new BullPillItem());
	public static final RegistryObject<Item> AIRPOD = REGISTRY.register("airpod", () -> new AirpodItem());
	public static final RegistryObject<Item> REMNANT = REGISTRY.register("remnant", () -> new RemnantItem());
	public static final RegistryObject<Item> KNOB = REGISTRY.register("knob", () -> new KnobItem());
	public static final RegistryObject<Item> RATS = REGISTRY.register("rats", () -> new RatsItem());
	public static final RegistryObject<Item> JOY_CONS = REGISTRY.register("joy_cons", () -> new JoyConsItem());
	public static final RegistryObject<Item> DRAWING_TABLET = REGISTRY.register("drawing_tablet", () -> new DrawingTabletItem());
	public static final RegistryObject<Item> VIOLIN = REGISTRY.register("violin", () -> new ViolinItem());
	public static final RegistryObject<Item> ANNOYING_DOG = REGISTRY.register("annoying_dog", () -> new AnnoyingDogItem());
	public static final RegistryObject<Item> GOLD_PLAY_BUTTON = REGISTRY.register("gold_play_button", () -> new GoldPlayButtonItem());
	public static final RegistryObject<Item> YEEZYS = REGISTRY.register("yeezys", () -> new YeezysItem());
	public static final RegistryObject<Item> CASSETTE_AGENT_RAINBOW = REGISTRY.register("cassette_agent_rainbow", () -> new CassetteAgentRainbowItem());
	public static final RegistryObject<Item> CASSETTE_VIRGINIA = REGISTRY.register("cassette_virginia", () -> new CassetteVirginiaItem());
	public static final RegistryObject<Item> CASSETTE_ALLEN = REGISTRY.register("cassette_allen", () -> new CassetteAllenItem());
	public static final RegistryObject<Item> CASSETTE_MAX = REGISTRY.register("cassette_max", () -> new CassetteMaxItem());
	public static final RegistryObject<Item> CASSETTE_LUCAS = REGISTRY.register("cassette_lucas", () -> new CassetteLucasItem());
	public static final RegistryObject<Item> CASSETTE_ROSE_MARY = REGISTRY.register("cassette_rose_mary", () -> new CassetteRoseMaryItem());
	public static final RegistryObject<Item> CASSETTE_DESMOND = REGISTRY.register("cassette_desmond", () -> new CassetteDesmondItem());
	public static final RegistryObject<Item> CASSETTE_MY_ORDINARY_LIFE = REGISTRY.register("cassette_my_ordinary_life", () -> new CassetteMyOrdinaryLifeItem());
	public static final RegistryObject<Item> CASSETTE_DRUNK = REGISTRY.register("cassette_drunk", () -> new CassetteDrunkItem());
	public static final RegistryObject<Item> CASSETTE_FNAF_1 = REGISTRY.register("cassette_fnaf_1", () -> new CassetteFnaf1Item());
	public static final RegistryObject<Item> CASSETTE_PARASITE = REGISTRY.register("cassette_parasite", () -> new CassetteParasiteItem());
	public static final RegistryObject<Item> CASSETTE_EISOPTROPHOBIA = REGISTRY.register("cassette_eisoptrophobia", () -> new CassetteEisoptrophobiaItem());
	public static final RegistryObject<Item> CASSETTE_DJMM = REGISTRY.register("cassette_djmm", () -> new CassetteDJMMItem());
	public static final RegistryObject<Item> CASSETTE_ROXANNE = REGISTRY.register("cassette_roxanne", () -> new CassetteRoxanneItem());
	public static final RegistryObject<Item> CASSETTE_ALWAYS_COME_BACK = REGISTRY.register("cassette_always_come_back", () -> new CassetteAlwaysComeBackItem());
	public static final RegistryObject<Item> CASSETTE_LEAVE_ME_BEHIND = REGISTRY.register("cassette_leave_me_behind", () -> new CassetteLeaveMeBehindItem());
	public static final RegistryObject<Item> CASSETTE_SANDCASTLE_KINGDOMS = REGISTRY.register("cassette_sandcastle_kingdoms", () -> new CassetteSandcastleKingdomsItem());
	public static final RegistryObject<Item> CASSETTE_BIG_POPPA = REGISTRY.register("cassette_big_poppa", () -> new CassetteBigPoppaItem());
	public static final RegistryObject<Item> CASSETTE_DOORS = REGISTRY.register("cassette_doors", () -> new CassetteDoorsItem());
	public static final RegistryObject<Item> CASSETTE_GUIDING_LIGHT = REGISTRY.register("cassette_guiding_light", () -> new CassetteGuidingLightItem());
	public static final RegistryObject<Item> CASSETTE_HERE_I_COME = REGISTRY.register("cassette_here_i_come", () -> new CassetteHereIComeItem());
	public static final RegistryObject<Item> CASSETTE_HERE_I_COME_2 = REGISTRY.register("cassette_here_i_come_2", () -> new CassetteHereICome2Item());
	public static final RegistryObject<Item> CASSETTE_FBC = REGISTRY.register("cassette_fbc", () -> new CassetteFBCItem());
	public static final RegistryObject<Item> CASSETTE_ARCHETYPE = REGISTRY.register("cassette_archetype", () -> new CassetteArchetypeItem());
	public static final RegistryObject<Item> CASSETTE_BATTLE_BLOCK = REGISTRY.register("cassette_battle_block", () -> new CassetteBattleBlockItem());
	public static final RegistryObject<Item> CASSETTE_BTD_5 = REGISTRY.register("cassette_btd_5", () -> new CassetteBTD5Item());
	public static final RegistryObject<Item> CASSETTE_TOMCAT = REGISTRY.register("cassette_tomcat", () -> new CassetteTomcatItem());
	public static final RegistryObject<Item> CASSETTE_NORMAL_ALBUM = REGISTRY.register("cassette_normal_album", () -> new CassetteNormalAlbumItem());
	public static final RegistryObject<Item> CASSETTE_OKULTRA = REGISTRY.register("cassette_okultra", () -> new CassetteOKULTRAItem());
	public static final RegistryObject<Item> CASSETTE_LOVE_ME_NORMALLY = REGISTRY.register("cassette_love_me_normally", () -> new CassetteLoveMeNormallyItem());
	public static final RegistryObject<Item> CASSETTE_PUPPETEER = REGISTRY.register("cassette_puppeteer", () -> new CassettePuppeteerItem());
	public static final RegistryObject<Item> CASSETTE_BUCKLE = REGISTRY.register("cassette_buckle", () -> new CassetteBuckleItem());
	public static final RegistryObject<Item> CASSETTE_TOACW = REGISTRY.register("cassette_toacw", () -> new CassetteTOACWItem());
	public static final RegistryObject<Item> CASSETTE_SLIME_GOD = REGISTRY.register("cassette_slime_god", () -> new CassetteSlimeGodItem());
	public static final RegistryObject<Item> CASSETTE_SCOURGE = REGISTRY.register("cassette_scourge", () -> new CassetteScourgeItem());
	public static final RegistryObject<Item> CASSETTE_UNIVERSAL_COLLAPSE = REGISTRY.register("cassette_universal_collapse", () -> new CassetteUniversalCollapseItem());
	public static final RegistryObject<Item> CASSETTE_JUNGLE_DRAGON = REGISTRY.register("cassette_jungle_dragon", () -> new CassetteJungleDragonItem());
	public static final RegistryObject<Item> CASSETTE_GHOSTS_N_STUFF = REGISTRY.register("cassette_ghosts_n_stuff", () -> new CassetteGhostsNStuffItem());
	public static final RegistryObject<Item> CASSETTE_BAD_END_THEATER = REGISTRY.register("cassette_bad_end_theater", () -> new CassetteBadEndTheaterItem());
	public static final RegistryObject<Item> CASSETTE_BARBIE = REGISTRY.register("cassette_barbie", () -> new CassetteBarbieItem());
	public static final RegistryObject<Item> CASSETTE_CALIFORNIA = REGISTRY.register("cassette_california", () -> new CassetteCaliforniaItem());
	public static final RegistryObject<Item> CASSETTE_ANARCHY_RAINBOW = REGISTRY.register("cassette_anarchy_rainbow", () -> new CassetteAnarchyRainbowItem());
	public static final RegistryObject<Item> CASSETTE_AMONGUS = REGISTRY.register("cassette_amongus", () -> new CassetteAmongusItem());
	public static final RegistryObject<Item> CASSETTE_FURRYMON = REGISTRY.register("cassette_furrymon", () -> new CassetteFurrymonItem());
	public static final RegistryObject<Item> CASSETTE_ETERNAL_HORIZONS = REGISTRY.register("cassette_eternal_horizons", () -> new CassetteEternalHorizonsItem());
	public static final RegistryObject<Item> CASSETTE_TOTTFIY = REGISTRY.register("cassette_tottfiy", () -> new CassetteTOTTFIYItem());
	public static final RegistryObject<Item> CASSETTE_GYM = REGISTRY.register("cassette_gym", () -> new CassetteGymItem());
	public static final RegistryObject<Item> CASSETTE_STEAM_GARDENS = REGISTRY.register("cassette_steam_gardens", () -> new CassetteSteamGardensItem());
	public static final RegistryObject<Item> CASSETTE_OOT = REGISTRY.register("cassette_oot", () -> new CassetteOOTItem());
	public static final RegistryObject<Item> CASSETTE_ISLAND = REGISTRY.register("cassette_island", () -> new CassetteIslandItem());
	public static final RegistryObject<Item> WILD_SIDE = REGISTRY.register("wild_side", () -> new WildSideItem());
	public static final RegistryObject<Item> CASSETTE_WOLF_AND_RABBIT = REGISTRY.register("cassette_wolf_and_rabbit", () -> new CassetteWolfAndRabbitItem());
	public static final RegistryObject<Item> CASSETTE_BOX_15 = REGISTRY.register("cassette_box_15", () -> new CassetteBox15Item());
	public static final RegistryObject<Item> CASSETTE_BOX_16 = REGISTRY.register("cassette_box_16", () -> new CassetteBox16Item());
	public static final RegistryObject<Item> CASSETTE_STILL_ALIVE = REGISTRY.register("cassette_still_alive", () -> new CassetteStillAliveItem());
	public static final RegistryObject<Item> CASSETTE_WANT_YOU_GONE = REGISTRY.register("cassette_want_you_gone", () -> new CassetteWantYouGoneItem());
	public static final RegistryObject<Item> CASSETTE_BETTY = REGISTRY.register("cassette_betty", () -> new CassetteBettyItem());
	public static final RegistryObject<Item> CASSETTE_1THOT_2THOT = REGISTRY.register("cassette_1thot_2thot", () -> new Cassette1thot2thotItem());
	public static final RegistryObject<Item> CASSETTE_CEST_LA_VIE = REGISTRY.register("cassette_cest_la_vie", () -> new CassetteCestLaVieItem());
	public static final RegistryObject<Item> CASSETTE_GOOD_MORNING = REGISTRY.register("cassette_good_morning", () -> new CassetteGoodMorningItem());
	public static final RegistryObject<Item> CASSETTE_STRONGER = REGISTRY.register("cassette_stronger", () -> new CassetteStrongerItem());
	public static final RegistryObject<Item> CASSETTE_AMERICAN_BOY = REGISTRY.register("cassette_american_boy", () -> new CassetteAmericanBoyItem());
	public static final RegistryObject<Item> CASSETTE_GRAVITY = REGISTRY.register("cassette_gravity", () -> new CassetteGravityItem());
	public static final RegistryObject<Item> CASSETTE_ADDICT = REGISTRY.register("cassette_addict", () -> new CassetteAddictItem());
	public static final RegistryObject<Item> CASSETTE_STOLAS = REGISTRY.register("cassette_stolas", () -> new CassetteStolasItem());
	public static final RegistryObject<Item> CASSETTE_SIMOON = REGISTRY.register("cassette_simoon", () -> new CassetteSimoonItem());
	public static final RegistryObject<Item> CASSETTE_GOD_RACE = REGISTRY.register("cassette_god_race", () -> new CassetteGodRaceItem());
	public static final RegistryObject<Item> CASSETTE_ANEMOIA = REGISTRY.register("cassette_anemoia", () -> new CassetteAnemoiaItem());
	public static final RegistryObject<Item> CASSETTE_ROCKY = REGISTRY.register("cassette_rocky", () -> new CassetteRockyItem());
	public static final RegistryObject<Item> CASSETTE_OLIVE_BRANCH = REGISTRY.register("cassette_olive_branch", () -> new CassetteOliveBranchItem());
	public static final RegistryObject<Item> CASSETTE_RASPUTIN = REGISTRY.register("cassette_rasputin", () -> new CassetteRasputinItem());
	public static final RegistryObject<Item> CASSETTE_KRATOS = REGISTRY.register("cassette_kratos", () -> new CassetteKratosItem());
	public static final RegistryObject<Item> CASSETTE_THUNDER = REGISTRY.register("cassette_thunder", () -> new CassetteThunderItem());
	public static final RegistryObject<Item> CASSETTE_HIGHWIRE = REGISTRY.register("cassette_highwire", () -> new CassetteHighwireItem());
	public static final RegistryObject<Item> CASSETTE_TOXIC_COFFEE = REGISTRY.register("cassette_toxic_coffee", () -> new CassetteToxicCoffeeItem());
	public static final RegistryObject<Item> CASSETTE_VIRTUAL_INSANITY = REGISTRY.register("cassette_virtual_insanity", () -> new CassetteVirtualInsanityItem());
	public static final RegistryObject<Item> CASSETTE_DREAMLAND = REGISTRY.register("cassette_dreamland", () -> new CassetteDreamlandItem());
	public static final RegistryObject<Item> CASSETTE_LIKE_THAT = REGISTRY.register("cassette_like_that", () -> new CassetteLikeThatItem());
	public static final RegistryObject<Item> CASSETTE_FINAL_DUET = REGISTRY.register("cassette_final_duet", () -> new CassetteFinalDuetItem());
	public static final RegistryObject<Item> CASSETTE_TULIPS = REGISTRY.register("cassette_tulips", () -> new CassetteTulipsItem());
	public static final RegistryObject<Item> CASSETTE_MY_TIME = REGISTRY.register("cassette_my_time", () -> new CassetteMyTimeItem());
	public static final RegistryObject<Item> CASSETTE_UNDERTALE = REGISTRY.register("cassette_undertale", () -> new CassetteUndertaleItem());
	public static final RegistryObject<Item> CASSETTE_DEATH_BY_GLAMOR = REGISTRY.register("cassette_death_by_glamor", () -> new CassetteDeathByGlamorItem());
	public static final RegistryObject<Item> CASSETTE_HOPES_AND_DREAMS = REGISTRY.register("cassette_hopes_and_dreams", () -> new CassetteHopesAndDreamsItem());
	public static final RegistryObject<Item> CASSETTE_TORIEL = REGISTRY.register("cassette_toriel", () -> new CassetteTorielItem());
	public static final RegistryObject<Item> CASSETTE_SCARLET_FOREST = REGISTRY.register("cassette_scarlet_forest", () -> new CassetteScarletForestItem());
	public static final RegistryObject<Item> CASSETTE_A_CYBERS_WORLD = REGISTRY.register("cassette_a_cybers_world", () -> new CassetteACybersWorldItem());
	public static final RegistryObject<Item> CASSETTE_SAFE_AND_SOUND = REGISTRY.register("cassette_safe_and_sound", () -> new CassetteSafeAndSoundItem());
	public static final RegistryObject<Item> CASSETTE_ASAFEWORLD = REGISTRY.register("cassette_asafeworld", () -> new CassetteASAFEWORLDItem());
	public static final RegistryObject<Item> CASSETTE_SAFE_AND_CYBER = REGISTRY.register("cassette_safe_and_cyber", () -> new CassetteSafeAndCYBERItem());
	public static final RegistryObject<Item> CASSETTE_BAKA_MITAI = REGISTRY.register("cassette_baka_mitai", () -> new CassetteBakaMitaiItem());
	public static final RegistryObject<Item> CASSETTE_LETTER_TO_MY_BROTHER = REGISTRY.register("cassette_letter_to_my_brother", () -> new CassetteLetterToMyBrotherItem());
	public static final RegistryObject<Item> CASSETTE_AFTER_DARK = REGISTRY.register("cassette_after_dark", () -> new CassetteAfterDarkItem());
	public static final RegistryObject<Item> CASSETTE_MONSTER = REGISTRY.register("cassette_monster", () -> new CassetteMonsterItem());
	public static final RegistryObject<Item> CASSETTE_IJAM = REGISTRY.register("cassette_ijam", () -> new CassetteIJAMItem());
	public static final RegistryObject<Item> CASSETTE_FMTTM = REGISTRY.register("cassette_fmttm", () -> new CassetteFMTTMItem());
	public static final RegistryObject<Item> CASSETTE_GOODBYE_TO_A_WORLD = REGISTRY.register("cassette_goodbye_to_a_world", () -> new CassetteGoodbyeToAWorldItem());
	public static final RegistryObject<Item> CASSETTE_REJUVENESCENCIA = REGISTRY.register("cassette_rejuvenescencia", () -> new CassetteRejuvenescenciaItem());
	public static final RegistryObject<Item> CASSETTE_WMTAO = REGISTRY.register("cassette_wmtao", () -> new CassetteWMTAOItem());
	public static final RegistryObject<Item> CASSETTE_BOW = REGISTRY.register("cassette_bow", () -> new CassetteBOWItem());
	public static final RegistryObject<Item> CASSETTE_GHOST = REGISTRY.register("cassette_ghost", () -> new CassetteGhostItem());
	public static final RegistryObject<Item> CASSETTE_WIGGLECORE = REGISTRY.register("cassette_wigglecore", () -> new CassetteWIGGLECOREItem());
	public static final RegistryObject<Item> CASSETTE_IF_WE_FALL = REGISTRY.register("cassette_if_we_fall", () -> new CassetteIfWeFallItem());
	public static final RegistryObject<Item> CASSETTE_KICK_BACK = REGISTRY.register("cassette_kick_back", () -> new CassetteKickBackItem());
	public static final RegistryObject<Item> CASSETTE_VAMPIRE = REGISTRY.register("cassette_vampire", () -> new CassetteVampireItem());
	public static final RegistryObject<Item> CASSETTE_LIGHTSABERS = REGISTRY.register("cassette_lightsabers", () -> new CassetteLightsabersItem());
	public static final RegistryObject<Item> CASSETTE_PIZZA_TIME = REGISTRY.register("cassette_pizza_time", () -> new CassettePizzaTimeItem());
	public static final RegistryObject<Item> CASSETTE_DAN_TDM = REGISTRY.register("cassette_dan_tdm", () -> new CassetteDanTDMItem());
	public static final RegistryObject<Item> CASSETTE_SCIENCE_BLASTER = REGISTRY.register("cassette_science_blaster", () -> new CassetteScienceBlasterItem());
	public static final RegistryObject<Item> CASSETTE_I_DONT_WANNA_BE_FREE = REGISTRY.register("cassette_i_dont_wanna_be_free", () -> new CassetteIDontWannaBeFreeItem());
	public static final RegistryObject<Item> CASSETTE_THE_LAST_GOODBYE = REGISTRY.register("cassette_the_last_goodbye", () -> new CassetteTheLastGoodbyeItem());
	public static final RegistryObject<Item> CASSETTE_COSMIC = REGISTRY.register("cassette_cosmic", () -> new CassetteCosmicItem());
	public static final RegistryObject<Item> CASSETTE_MATTEL = REGISTRY.register("cassette_mattel", () -> new CassetteMattelItem());
	public static final RegistryObject<Item> CASSETTE_G = REGISTRY.register("cassette_g", () -> new CassetteGItem());
	public static final RegistryObject<Item> CASSETTE_NIGHTMARE = REGISTRY.register("cassette_nightmare", () -> new CassetteNightmareItem());
	public static final RegistryObject<Item> CASSETTE_LOVE_LIKE_YOU = REGISTRY.register("cassette_love_like_you", () -> new CassetteLoveLikeYouItem());
	public static final RegistryObject<Item> CASSETTE_2_TIME_ZONES = REGISTRY.register("cassette_2_time_zones", () -> new Cassette2TimeZonesItem());
	public static final RegistryObject<Item> CASSETTE_PIGSTEP = REGISTRY.register("cassette_pigstep", () -> new CassettePigstepItem());
	public static final RegistryObject<Item> CASSETTE_PIGSTEP_JAZZ = REGISTRY.register("cassette_pigstep_jazz", () -> new CassettePigstepJazzItem());
	public static final RegistryObject<Item> CASSETTE_ALPHA = REGISTRY.register("cassette_alpha", () -> new CassetteAlphaItem());
	public static final RegistryObject<Item> CASSETTE_MOV = REGISTRY.register("cassette_mov", () -> new CassetteMOVItem());
	public static final RegistryObject<Item> HANDSOME_DEVIL = REGISTRY.register("handsome_devil", () -> new HandsomeDevilItem());
}
